name: Seed GitHub Issues

on:
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Issues from YAML
        uses: Avalanche-Team1-Africa/create-issues-action@main
        with:
          filename: .github/issues.yml
